# Generated by Django 5.0.4 on 2024-06-10 09:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_payments_payment_date_alter_payments_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='payment_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 10, 17, 9, 0, 781720), verbose_name='Дата оплаты'),
        ),
    ]
