# Generated by Django 5.0.4 on 2024-06-10 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_payments_payment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='payment_date',
            field=models.DateTimeField(verbose_name='Дата оплаты'),
        ),
    ]
