# Generated by Django 5.0.4 on 2024-06-05 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0008_alter_lesson_course_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='amount',
            field=models.IntegerField(default=1000, verbose_name='Цена'),
        ),
    ]
